import{S as d,i}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function p(s){const o=document.querySelector(".gallery");function r(e){const t=e.webformatURL,n=e.largeImageURL,c=e.tags,l=e.likes,u=e.views,m=e.comments,f=e.downloads;return`<div class="card">
            <a href='${n}' class="large-image-link">
              <img class="image" src='${t}' alt="${c}">
              <div class="info">
                <p class="info-item"><span class="info-header">Likes</span><br>${l}</p>
                <p class="info-item"><span class="info-header">Views</span><br>${u}</p>
                <p class="info-item"><span class="info-header">Comments</span><br>${m}</p>
                <p class="info-item"><span class="info-header">Downloads</span><br>${f}</p>
              </div>
            </a>
          </div>`}o.innerHTML="",s.forEach(e=>{const t=r(e);o.insertAdjacentHTML("beforeend",t)}),new d(".large-image-link").refresh()}const h=document.querySelector(".searchInput"),g="42324270-89622daef349524aeb531ebd1",y="https://pixabay.com/api/",b="image_type=photo&orientation=horizontal&safesearch=true";function w(){const s=h.value.trim(),o=`${y}?key=${g}&q=${s}&${b}`;return fetch(o).then(r=>{if(!r.ok)throw new Error("Image error!");return r.json()}).then(r=>{r.hits.length===0?i.show({position:"topRight",timeout:3500,message:"Sorry, there are no images matching your search query. Please try again!",close:!1,messageColor:"white",backgroundColor:"green"}):p(r.hits)}).catch(r=>{alert("Error while rendering images")})}const L=document.querySelector(".submitForm"),v=document.querySelector(".searchInput");document.querySelector(".loader");L.addEventListener("submit",s=>{if(s.preventDefault(),v.value.trim()===""){i.show({position:"topRight",timeout:2e3,message:"Please, enter the word!",close:!1,messageColor:"white",backgroundColor:"grey"});return}w()});
//# sourceMappingURL=commonHelpers.js.map
