import{S as p,i as c}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function h(o){const s=document.querySelector(".gallery");function r(e){const t=e.webformatURL,n=e.largeImageURL,l=e.tags,u=e.likes,d=e.views,m=e.comments,f=e.downloads;return`<div class="card">
            <a href='${n}' class="large-image-link">
              <img class="image" src='${t}' alt="${l}">
              <div class="info">
                <p class="info-item"><span class="info-header">Likes</span><br>${u}</p>
                <p class="info-item"><span class="info-header">Views</span><br>${d}</p>
                <p class="info-item"><span class="info-header">Comments</span><br>${m}</p>
                <p class="info-item"><span class="info-header">Downloads</span><br>${f}</p>
              </div>
            </a>
          </div>`}s.innerHTML="",o.forEach(e=>{const t=r(e);s.insertAdjacentHTML("beforeend",t)}),new p(".large-image-link").refresh()}const g=document.querySelector(".searchInput"),i=document.querySelector(".loader"),y="42324270-89622daef349524aeb531ebd1",b="https://pixabay.com/api/",w="image_type=photo&orientation=horizontal&safesearch=true";function L(){const o=g.value.trim(),s=`${b}?key=${y}&q=${o}&${w}`;return i.classList.remove("hidden"),fetch(s).then(r=>{if(!r.ok)throw new Error("Image error!");return r.json()}).then(r=>{r.hits.length===0?c.show({position:"topRight",timeout:3500,message:"Sorry, there are no images matching your search query. Please try again!",close:!1,messageColor:"white",backgroundColor:"green"}):h(r.hits)}).catch(r=>{alert("Error while rendering images")}).finally(()=>{i.classList.add("hidden")})}const v=document.querySelector(".submitForm"),$=document.querySelector(".searchInput");v.addEventListener("submit",o=>{if(o.preventDefault(),$.value.trim()===""){c.show({position:"topRight",timeout:2e3,message:"Please, enter the word!",close:!1,messageColor:"white",backgroundColor:"grey"});return}L()});
//# sourceMappingURL=commonHelpers.js.map
